// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB__4kLCmcmjs9yQ1lFzGJ5-nbbMnGjSuY',
    appId: '1:569284055882:web:f44872455396174c5c67b3',
    messagingSenderId: '569284055882',
    projectId: 'graduation-project-9d299',
    authDomain: 'graduation-project-9d299.firebaseapp.com',
    storageBucket: 'graduation-project-9d299.appspot.com',
    measurementId: 'G-LXK8KB3M6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRJUlUy-zM7nOIwUvuhUxk63NxN4kPiDo',
    appId: '1:569284055882:android:2efbd101539dc4635c67b3',
    messagingSenderId: '569284055882',
    projectId: 'graduation-project-9d299',
    storageBucket: 'graduation-project-9d299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvqB8gy3KWaR8kagb8iZ7RLcykrXtHGhM',
    appId: '1:569284055882:ios:771d6819df07364e5c67b3',
    messagingSenderId: '569284055882',
    projectId: 'graduation-project-9d299',
    storageBucket: 'graduation-project-9d299.appspot.com',
    iosBundleId: 'com.example.gradiuationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvqB8gy3KWaR8kagb8iZ7RLcykrXtHGhM',
    appId: '1:569284055882:ios:771d6819df07364e5c67b3',
    messagingSenderId: '569284055882',
    projectId: 'graduation-project-9d299',
    storageBucket: 'graduation-project-9d299.appspot.com',
    iosBundleId: 'com.example.gradiuationProject',
  );
}
